repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b # v0.15.22
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
      - id: ruff-format
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        exclude: '^(uv\.lock)$'

  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: ac85803d0443afba1e0700690366fd2d39e02580 # v0.0.65
    hooks:
      - id: ty